---
- name: Add SBT repo
  apt_repository: repo='deb https://dl.bintray.com/sbt/debian /' state=present
  become: yes

- name: Add SBT repo key
  apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id='642AC823'
  become: yes

- name: Install SBT
  apt: name=sbt state=latest update_cache=yes allow_unauthenticated=yes
  become: yes